### ISSUE TITLE
Dicremote isn't able to make a connection when using an internal IP address

### ISSUE THREAD

**Issue by TheRogueArchivist** [discimagechef/dicremote#2]
Dicremote doesn't establish a connection when I try to connect to it through its internal IP address. Instead, I have to set up port forwarding to the internal IP and then connect to it using my public IP address. This could be a problem for allowing more than one dicremote instance to be used in a single network at the same time.

**Comment by claunia** [comment]
Sorry but you'll have to be more specific, what are the IPs, how are the machines connected, is it a switch, a hub, a router?

**Comment by TheRogueArchivist** [comment]
The IPs are the local 192.168.x.x addresses used by the router, and they're only connected through the network using the router. It works fine if I use port forwarding to send traffic for that port to the right computer and give DIC my public IP address to connect to.

**Comment by claunia** [comment]
Please give a complete drawing of the physical connections and the IPs address of each apparatus in the network between dic and dicremote (can be in private).

**Comment by claunia** [comment]
I think this was fixed in https://github.com/aaru-dps/Aaru/commit/3f9a0631f0e127b83c27b3cbbbe3d0c3d71c32fd @silaslaspada please check.

**Comment by TheRogueArchivist** [comment]
Is indeed fixed
